# Generated by Django 4.0.3 on 2022-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alter_ego', models.CharField(max_length=200)),
                ('primary_ability', models.CharField(max_length=200)),
                ('secondary_ability', models.CharField(max_length=200)),
                ('catchphrase', models.CharField(max_length=200)),
            ],
        ),
    ]
