# Generated by Django 4.0.3 on 2022-04-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supers',
            name='supers_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supers_types.super_types'),
            preserve_default=False,
        ),
    ]
